<?php

namespace AppBundle\Repository;

/**
 * modificationClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class modificationClientRepository extends \Doctrine\ORM\EntityRepository
{
}
