<?php

namespace AppBundle\Repository;

/**
 * MouchardRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MouchardRepository extends \Doctrine\ORM\EntityRepository
{
}
