<?php

namespace AppBundle\Repository;

/**
 * PersonneMoralRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonneMoralRepository extends \Doctrine\ORM\EntityRepository
{
}
