<?php

namespace AppBundle\Repository;

/**
 * personnePhysiqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class personnePhysiqueRepository extends \Doctrine\ORM\EntityRepository
{
}
