<?php

namespace AppBundle\Repository;

/**
 * proprietaireCompteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class proprietaireCompteRepository extends \Doctrine\ORM\EntityRepository
{
}
