<?php

namespace AppBundle\Repository;

/**
 * schemaOperationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class schemaOperationRepository extends \Doctrine\ORM\EntityRepository
{
}
