<?php

namespace AppBundle\Repository;

/**
 * SignataireCompteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SignataireCompteRepository extends \Doctrine\ORM\EntityRepository
{
}
