<?php

namespace AppBundle\Repository;

/**
 * SignataireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SignataireRepository extends \Doctrine\ORM\EntityRepository
{
}
