<?php

namespace AppBundle\Repository;

/**
 * typeOperationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class typeOperationRepository extends \Doctrine\ORM\EntityRepository
{
}
