<?php

namespace AppBundle\Repository;

/**
 * utilisateurCaisseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class utilisateurCaisseRepository extends \Doctrine\ORM\EntityRepository
{
}
