# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_AGENT:       ROLE_USER
        ROLE_COMPTABLE:   ROLE_AGENT
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        ROLE_CHEF_COMPTABLE: ROLE_COMPTABLE
        ROLE_CONTROLEUR: ROLE_CHEF_COMPTABLE
        ROLE_CHEF_CONTROLEUR: ROLE_CONTROLEUR

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        webservice:
            id: user.webserviceprovider


    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            logout:
                path:   /logout
                target: /login
            guard:
                authenticators:
                    - form_authenticator
            provider: webservice

    access_control:
            - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/api, roles: IS_AUTHENTICATED_ANONYMOUSLY }
            #- { path: ^/, roles: ROLE_ADMIN }
            #- { path: ^/, roles: IS_AUTHENTICATED_FULLY }
