<?php

namespace UserBundle\Repository;

/**
 * UserUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserUserRepository extends \Doctrine\ORM\EntityRepository
{
}
